#!/bin/bash
# tools/alacritty/lib/emit.sh
#
# Serializes the CFG associative array (populated by the wizard) into the
# split ~/.config/alacritty/ file tree, with backup + validation.
#
# CFG is a flat, dotted-key associative array whose values are ALREADY
# valid TOML literals (e.g. CFG[font.size]='13.0', CFG[window.decorations]='"Full"').
# Only the keys the wizard actually visited are present; emit_* functions
# treat every field as optional and fall back to omitting it (letting
# Alacritty's own default apply).

declare -A CFG
IMPORT_PATHS=()
BACKED_UP_FILES=()

emit_cfg_get() {
	local key="$1" default="${2:-}"
	if [[ -v "CFG[$key]" ]]; then
		printf '%s' "${CFG[$key]}"
	else
		printf '%s' "$default"
	fi
}

emit_has() {
	[[ -v "CFG[$1]" ]]
}

# emit_backup <path> -- copies an existing file aside before it is overwritten.
emit_backup() {
	local path="$1"
	[[ -f "$path" ]] || return 0
	local ts backup
	ts="$(date +%Y%m%d-%H%M%S)"
	backup="${path}.bak.${ts}"
	cp -p "$path" "$backup"
	BACKED_UP_FILES+=("$backup")
}

# emit_write <path> <content> -- backs up any existing file, then writes.
emit_write() {
	local path="$1" content="$2"
	mkdir -p "$(dirname "$path")"
	emit_backup "$path"
	printf '%s\n' "$content" >"$path"
}

# emit_restore_backups -- restores every path in BACKED_UP_FILES to its
# original location (used when validation fails after a write).
emit_restore_backups() {
	local backup orig
	for backup in "${BACKED_UP_FILES[@]}"; do
		orig="${backup%.bak.*}"
		cp -p "$backup" "$orig"
		ui_warn "Restored $orig from $backup"
	done
}

emit_header() {
	cat <<EOF
# Generated by tools/alacritty/alacritty-configure on $(date '+%Y-%m-%d %H:%M:%S')
# Re-run the wizard at any time to reconfigure: tools/alacritty/alacritty-configure
EOF
}

# emit_general_toml -- the [general]/[env]/[window]/[scrolling]/[font]/
# [bell]/[selection]/[cursor]/[terminal]/[mouse] tables, in the order
# documented by `man 5 alacritty`.
emit_general_toml() {
	emit_header
	printf '\n'

	if [[ "${#IMPORT_PATHS[@]}" -gt 0 || $(emit_has general.live_config_reload && echo 1) == "1" ]]; then
		printf '[general]\n'
		if [[ "${#IMPORT_PATHS[@]}" -gt 0 ]]; then
			printf 'import = [\n'
			local p
			for p in "${IMPORT_PATHS[@]}"; do
				printf '  "%s",\n' "$p"
			done
			printf ']\n'
		fi
		emit_has general.live_config_reload && printf 'live_config_reload = %s\n' "$(emit_cfg_get general.live_config_reload)"
		printf '\n'
	fi

	local -a window_keys=(
		window.opacity window.blur window.dynamic_padding window.decorations
		window.decorations_theme_variant window.startup_mode window.dynamic_title
	)
	local any_window=0
	local k
	for k in "${window_keys[@]}"; do
		emit_has "$k" && any_window=1
	done
	if [[ "$any_window" -eq 1 || $(emit_cfg_get window.padding.x) != "" ]]; then
		printf '[window]\n'
		emit_has window.padding.x && printf 'padding = { x = %s, y = %s }\n' "$(emit_cfg_get window.padding.x 0)" "$(emit_cfg_get window.padding.y 0)"
		emit_has window.dynamic_padding && printf 'dynamic_padding = %s\n' "$(emit_cfg_get window.dynamic_padding)"
		emit_has window.decorations && printf 'decorations = %s\n' "$(emit_cfg_get window.decorations)"
		emit_has window.decorations_theme_variant && printf 'decorations_theme_variant = %s\n' "$(emit_cfg_get window.decorations_theme_variant)"
		emit_has window.opacity && printf 'opacity = %s\n' "$(emit_cfg_get window.opacity)"
		emit_has window.blur && printf 'blur = %s\n' "$(emit_cfg_get window.blur)"
		emit_has window.startup_mode && printf 'startup_mode = %s\n' "$(emit_cfg_get window.startup_mode)"
		emit_has window.dynamic_title && printf 'dynamic_title = %s\n' "$(emit_cfg_get window.dynamic_title)"
		if emit_has window.dimensions.columns; then
			printf 'dimensions = { columns = %s, lines = %s }\n' "$(emit_cfg_get window.dimensions.columns)" "$(emit_cfg_get window.dimensions.lines)"
		fi
		printf '\n'
	fi

	if emit_has scrolling.history || emit_has scrolling.multiplier; then
		printf '[scrolling]\n'
		emit_has scrolling.history && printf 'history = %s\n' "$(emit_cfg_get scrolling.history)"
		emit_has scrolling.multiplier && printf 'multiplier = %s\n' "$(emit_cfg_get scrolling.multiplier)"
		printf '\n'
	fi

	if emit_has font.normal.family; then
		printf '[font]\n'
		printf 'normal = { family = %s, style = %s }\n' "$(emit_cfg_get font.normal.family)" "$(emit_cfg_get font.normal.style '"Regular"')"
		emit_has font.bold.family && printf 'bold = { family = %s, style = %s }\n' "$(emit_cfg_get font.bold.family)" "$(emit_cfg_get font.bold.style '"Bold"')"
		emit_has font.italic.family && printf 'italic = { family = %s, style = %s }\n' "$(emit_cfg_get font.italic.family)" "$(emit_cfg_get font.italic.style '"Italic"')"
		emit_has font.bold_italic.family && printf 'bold_italic = { family = %s, style = %s }\n' "$(emit_cfg_get font.bold_italic.family)" "$(emit_cfg_get font.bold_italic.style '"Bold Italic"')"
		emit_has font.size && printf 'size = %s\n' "$(emit_cfg_get font.size 12.0)"
		emit_has font.builtin_box_drawing && printf 'builtin_box_drawing = %s\n' "$(emit_cfg_get font.builtin_box_drawing)"
		printf '\n'
	fi

	if emit_has colors.draw_bold_text_with_bright_colors || emit_has colors.transparent_background_colors; then
		printf '[colors]\n'
		emit_has colors.draw_bold_text_with_bright_colors && printf 'draw_bold_text_with_bright_colors = %s\n' "$(emit_cfg_get colors.draw_bold_text_with_bright_colors)"
		emit_has colors.transparent_background_colors && printf 'transparent_background_colors = %s\n' "$(emit_cfg_get colors.transparent_background_colors)"
		printf '\n'
	fi

	if emit_has bell.animation; then
		printf '[bell]\n'
		printf 'animation = %s\n' "$(emit_cfg_get bell.animation)"
		emit_has bell.duration && printf 'duration = %s\n' "$(emit_cfg_get bell.duration)"
		emit_has bell.color && printf 'color = %s\n' "$(emit_cfg_get bell.color)"
		printf '\n'
	fi

	if emit_has selection.save_to_clipboard || emit_has selection.semantic_escape_chars; then
		printf '[selection]\n'
		emit_has selection.save_to_clipboard && printf 'save_to_clipboard = %s\n' "$(emit_cfg_get selection.save_to_clipboard)"
		emit_has selection.semantic_escape_chars && printf 'semantic_escape_chars = %s\n' "$(emit_cfg_get selection.semantic_escape_chars)"
		printf '\n'
	fi

	if emit_has cursor.style.shape; then
		printf '[cursor]\n'
		printf 'style = { shape = %s, blinking = %s }\n' "$(emit_cfg_get cursor.style.shape)" "$(emit_cfg_get cursor.style.blinking '"Off"')"
		emit_has cursor.unfocused_hollow && printf 'unfocused_hollow = %s\n' "$(emit_cfg_get cursor.unfocused_hollow)"
		emit_has cursor.thickness && printf 'thickness = %s\n' "$(emit_cfg_get cursor.thickness)"
		emit_has cursor.blink_interval && printf 'blink_interval = %s\n' "$(emit_cfg_get cursor.blink_interval)"
		emit_has cursor.blink_timeout && printf 'blink_timeout = %s\n' "$(emit_cfg_get cursor.blink_timeout)"
		printf '\n'
	fi

	if emit_has terminal.shell.program; then
		printf '[terminal]\n'
		if emit_has terminal.shell.args; then
			printf 'shell = { program = %s, args = %s }\n' "$(emit_cfg_get terminal.shell.program)" "$(emit_cfg_get terminal.shell.args)"
		else
			printf 'shell = %s\n' "$(emit_cfg_get terminal.shell.program)"
		fi
		printf '\n'
	fi

	if emit_has mouse.hide_when_typing; then
		printf '[mouse]\n'
		printf 'hide_when_typing = %s\n' "$(emit_cfg_get mouse.hide_when_typing)"
		printf '\n'
	fi
}

# emit_keybindings_toml <preset> -- prints a [keyboard] table for the given
# preset name (minimal|standard|standard_shell).
emit_keybindings_toml() {
	local preset="$1"
	emit_header
	printf '\n'
	case "$preset" in
	minimal)
		printf '# Minimal preset selected: no custom keybindings (Alacritty defaults apply).\n'
		return
		;;
	standard | standard_shell)
		cat <<'EOF'
[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "F", mods = "Control|Shift", action = "SearchForward" },
  { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
  { key = "F11", action = "ToggleFullscreen" },
EOF
		;;
	esac

	if [[ "$preset" == "standard_shell" ]]; then
		cat <<'EOF'
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" },
  { key = "Backspace", mods = "Control", chars = "\u0017" },
  { key = "Insert", mods = "Shift", action = "Paste" },
EOF
	fi

	printf ']\n'
}

# emit_hints_toml -- prints a [hints] table enabling URL hints via xdg-open.
emit_hints_toml() {
	emit_header
	printf '\n'
	cat <<'EOF'
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
EOF
}

# emit_all <config_dir> <theme_toml_content> <theme_filename> <keybind_preset> <hints_enabled>
# Orchestrates writing every file, then validates and rolls back on failure.
emit_all() {
	local config_dir="$1" theme_content="$2" theme_filename="$3" keybind_preset="$4" hints_enabled="$5"

	BACKED_UP_FILES=()
	IMPORT_PATHS=()

	# Imports must resolve correctly regardless of where the config tree is
	# rooted: use the canonical "~/..." form only when writing to the real,
	# default Alacritty config directory; otherwise use an absolute path so
	# --output-dir trees (e.g. for testing) are self-contained.
	local import_prefix="$config_dir"
	if [[ "$config_dir" == "${XDG_CONFIG_HOME:-$HOME/.config}/alacritty" ]]; then
		import_prefix="~/.config/alacritty"
	fi

	if [[ -n "$theme_filename" ]]; then
		emit_write "$config_dir/themes/$theme_filename" "$theme_content"
		IMPORT_PATHS+=("$import_prefix/themes/$theme_filename")
	fi

	if [[ -n "$keybind_preset" && "$keybind_preset" != "minimal" ]]; then
		emit_write "$config_dir/keybindings.toml" "$(emit_keybindings_toml "$keybind_preset")"
		IMPORT_PATHS+=("$import_prefix/keybindings.toml")
	fi

	if [[ "$hints_enabled" == "y" ]]; then
		emit_write "$config_dir/hints.toml" "$(emit_hints_toml)"
		IMPORT_PATHS+=("$import_prefix/hints.toml")
	fi

	emit_write "$config_dir/alacritty.toml" "$(emit_general_toml)"

	if ! emit_validate "$config_dir/alacritty.toml"; then
		ui_error "Generated configuration failed validation. Rolling back."
		emit_restore_backups
		return 1
	fi

	return 0
}

# emit_validate <path> -- uses `alacritty migrate --dry-run` to sanity check
# the emitted TOML without touching the live config.
emit_validate() {
	local path="$1"
	if ! command -v "$ALACRITTY_BIN" >/dev/null 2>&1 && [[ -z "$ALACRITTY_BIN" ]]; then
		return 0
	fi
	"$ALACRITTY_BIN" migrate --dry-run --silent -c "$path" >/tmp/alacritty-configure-validate.$$ 2>&1
	local rc=$?
	if [[ "$rc" -ne 0 ]]; then
		cat /tmp/alacritty-configure-validate.$$ >&2
	fi
	rm -f /tmp/alacritty-configure-validate.$$
	return "$rc"
}

# emit_reset_preview -- clears any runtime `alacritty msg config` overrides.
emit_reset_preview() {
	[[ "$LIVE" -eq 1 ]] || return 0
	"$ALACRITTY_BIN" msg config --reset -w -1 >/dev/null 2>&1
}
