#!/bin/bash
# lib/p10k.sh
#
# Powerlevel10k configuration helper for the setup wizard.

P10K_DIR="$HOME/.oh-my-zsh/custom/themes/powerlevel10k"

# p10k_minimal_template -- used when the full p10k-lean template is not available.
p10k_minimal_template() {
	cat <<'EOF'
# Generated by alacritty-configure
# Minimal Powerlevel10k configuration. For more options, run `p10k configure`.

# Prompt segments.
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time time)

# The rest uses Powerlevel10k defaults.
EOF
}

# p10k_setup_zshrc -- makes sure ~/.zshrc uses powerlevel10k and sources ~/.p10k.zsh
p10k_setup_zshrc() {
	local zshrc="$HOME/.zshrc"
	[[ ! -f "$zshrc" ]] && return 0

	if ! grep -q '^ZSH_THEME=' "$zshrc"; then
		printf 'ZSH_THEME="powerlevel10k/powerlevel10k"\n' >>"$zshrc"
	else
		sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' "$zshrc"
	fi

	if ! grep -q '\.p10k\.zsh' "$zshrc"; then
		printf '\n# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.\n' >>"$zshrc"
		printf '[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh\n' >>"$zshrc"
	fi
}

# write_p10k_config <mode> <os_icon> <prompt_char>
# mode: nerdfont-v3 or powerline
# os_icon/prompt_char: y or n
write_p10k_config() {
	local mode="$1" os_icon="$2" prompt_char="$3"
	local p10k_path="$HOME/.p10k.zsh"
	local base="$P10K_DIR/config/p10k-lean.zsh"

	local content=""
	if [[ -f "$base" ]]; then
		content="$(cat "$base")"
	else
		content="$(p10k_minimal_template)"
	fi

	# Build the left prompt segment list based on the user's choices.
	local -a left=(dir vcs)
	if [[ "$os_icon" == "y" ]]; then
		left=(os_icon "${left[@]}")
	fi
	if [[ "$prompt_char" == "y" ]]; then
		left+=(newline prompt_char)
	fi

	# Append override values at the end of the file. In Powerlevel10k these
	# globals are set with `typeset -g`, so the last definition wins.
	content+=$'\n'
	content+=$'# Overridden by alacritty-configure\n'
	content+="typeset -g POWERLEVEL9K_MODE=${mode}"$'\n'
	content+="typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( ${left[*]} )"$'\n'

	if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
		ui_info "Would write ${p10k_path}:"
		printf '%s\n' "$content"
		return 0
	fi

	if [[ -f "$p10k_path" ]]; then
		cp -p "$p10k_path" "${p10k_path}.bak.$(date +%Y%m%d-%H%M%S)"
	fi
	printf '%s\n' "$content" >"$p10k_path"

	p10k_setup_zshrc
	ui_success "Wrote Powerlevel10k configuration to ${p10k_path}"
}
