#!/bin/bash
# tools/alacritty/lib/themes.sh
#
# Eight embedded color themes plus an optional fetch of the full upstream
# alacritty/alacritty-theme collection.

THEME_NAMES=(gruvbox_dark catppuccin_mocha tokyo_night nord dracula solarized_dark solarized_light one_dark)
THEME_LABELS=("Gruvbox Dark" "Catppuccin Mocha" "Tokyo Night" "Nord" "Dracula" "Solarized Dark" "Solarized Light" "One Dark")

# Each theme_hex_<name> function sets the THX assoc array with keys:
# bg fg cursor black red green yellow blue magenta cyan white
# bblack bred bgreen byellow bblue bmagenta bcyan bwhite

declare -A THX

theme_hex_gruvbox_dark() {
	THX=(
		[bg]="#282828" [fg]="#ebdbb2" [cursor]="#ebdbb2"
		[black]="#282828" [red]="#cc241d" [green]="#98971a" [yellow]="#d79921"
		[blue]="#458588" [magenta]="#b16286" [cyan]="#689d6a" [white]="#a89984"
		[bblack]="#928374" [bred]="#fb4934" [bgreen]="#b8bb26" [byellow]="#fabd2f"
		[bblue]="#83a598" [bmagenta]="#d3869b" [bcyan]="#8ec07c" [bwhite]="#ebdbb2"
	)
}

theme_hex_catppuccin_mocha() {
	THX=(
		[bg]="#1e1e2e" [fg]="#cdd6f4" [cursor]="#f5e0dc"
		[black]="#45475a" [red]="#f38ba8" [green]="#a6e3a1" [yellow]="#f9e2af"
		[blue]="#89b4fa" [magenta]="#f5c2e7" [cyan]="#94e2d5" [white]="#bac2de"
		[bblack]="#585b70" [bred]="#f38ba8" [bgreen]="#a6e3a1" [byellow]="#f9e2af"
		[bblue]="#89b4fa" [bmagenta]="#f5c2e7" [bcyan]="#94e2d5" [bwhite]="#a6adc8"
	)
}

theme_hex_tokyo_night() {
	THX=(
		[bg]="#1a1b26" [fg]="#c0caf5" [cursor]="#c0caf5"
		[black]="#15161e" [red]="#f7768e" [green]="#9ece6a" [yellow]="#e0af68"
		[blue]="#7aa2f7" [magenta]="#bb9af7" [cyan]="#7dcfff" [white]="#a9b1d6"
		[bblack]="#414868" [bred]="#f7768e" [bgreen]="#9ece6a" [byellow]="#e0af68"
		[bblue]="#7aa2f7" [bmagenta]="#bb9af7" [bcyan]="#7dcfff" [bwhite]="#c0caf5"
	)
}

theme_hex_nord() {
	THX=(
		[bg]="#2e3440" [fg]="#d8dee9" [cursor]="#d8dee9"
		[black]="#3b4252" [red]="#bf616a" [green]="#a3be8c" [yellow]="#ebcb8b"
		[blue]="#81a1c1" [magenta]="#b48ead" [cyan]="#88c0d0" [white]="#e5e9f0"
		[bblack]="#4c566a" [bred]="#bf616a" [bgreen]="#a3be8c" [byellow]="#ebcb8b"
		[bblue]="#81a1c1" [bmagenta]="#b48ead" [bcyan]="#8fbcbb" [bwhite]="#eceff4"
	)
}

theme_hex_dracula() {
	THX=(
		[bg]="#282a36" [fg]="#f8f8f2" [cursor]="#f8f8f2"
		[black]="#21222c" [red]="#ff5555" [green]="#50fa7b" [yellow]="#f1fa8c"
		[blue]="#bd93f9" [magenta]="#ff79c6" [cyan]="#8be9fd" [white]="#f8f8f2"
		[bblack]="#6272a4" [bred]="#ff6e6e" [bgreen]="#69ff94" [byellow]="#ffffa5"
		[bblue]="#d6acff" [bmagenta]="#ff92df" [bcyan]="#a4ffff" [bwhite]="#ffffff"
	)
}

theme_hex_solarized_dark() {
	THX=(
		[bg]="#002b36" [fg]="#839496" [cursor]="#839496"
		[black]="#073642" [red]="#dc322f" [green]="#859900" [yellow]="#b58900"
		[blue]="#268bd2" [magenta]="#d33682" [cyan]="#2aa198" [white]="#eee8d5"
		[bblack]="#586e75" [bred]="#cb4b16" [bgreen]="#93a1a1" [byellow]="#657b83"
		[bblue]="#839496" [bmagenta]="#6c71c4" [bcyan]="#93a1a1" [bwhite]="#fdf6e3"
	)
}

theme_hex_solarized_light() {
	THX=(
		[bg]="#fdf6e3" [fg]="#657b83" [cursor]="#657b83"
		[black]="#073642" [red]="#dc322f" [green]="#859900" [yellow]="#b58900"
		[blue]="#268bd2" [magenta]="#d33682" [cyan]="#2aa198" [white]="#eee8d5"
		[bblack]="#586e75" [bred]="#cb4b16" [bgreen]="#93a1a1" [byellow]="#839496"
		[bblue]="#657b83" [bmagenta]="#6c71c4" [bcyan]="#93a1a1" [bwhite]="#fdf6e3"
	)
}

theme_hex_one_dark() {
	THX=(
		[bg]="#282c34" [fg]="#abb2bf" [cursor]="#abb2bf"
		[black]="#282c34" [red]="#e06c75" [green]="#98c379" [yellow]="#e5c07b"
		[blue]="#61afef" [magenta]="#c678dd" [cyan]="#56b6c2" [white]="#dcdfe4"
		[bblack]="#545862" [bred]="#e06c75" [bgreen]="#98c379" [byellow]="#e5c07b"
		[bblue]="#61afef" [bmagenta]="#c678dd" [bcyan]="#56b6c2" [bwhite]="#ffffff"
	)
}

# theme_load_hex <name> -- populates THX for the given embedded theme name.
theme_load_hex() {
	"theme_hex_$1"
}

# theme_toml <name> -- prints the [colors] TOML block for an embedded theme.
theme_toml() {
	local name="$1"
	theme_load_hex "$name"
	cat <<EOF
# ${name}.toml -- generated by tools/alacritty/alacritty-configure

[colors.primary]
background = "${THX[bg]}"
foreground = "${THX[fg]}"

[colors.cursor]
cursor = "${THX[cursor]}"
text = "${THX[bg]}"

[colors.normal]
black   = "${THX[black]}"
red     = "${THX[red]}"
green   = "${THX[green]}"
yellow  = "${THX[yellow]}"
blue    = "${THX[blue]}"
magenta = "${THX[magenta]}"
cyan    = "${THX[cyan]}"
white   = "${THX[white]}"

[colors.bright]
black   = "${THX[bblack]}"
red     = "${THX[bred]}"
green   = "${THX[bgreen]}"
yellow  = "${THX[byellow]}"
blue    = "${THX[bblue]}"
magenta = "${THX[bmagenta]}"
cyan    = "${THX[bcyan]}"
white   = "${THX[bwhite]}"
EOF
}

# theme_hex_to_rgb "#rrggbb" -> "r;g;b"
theme_hex_to_rgb() {
	local hex="${1#\#}"
	printf '%d;%d;%d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# theme_preview_loaded -- renders the swatch + mock prompt/diff panel using
# the colors already loaded into the global THX array.
theme_preview_loaded() {
	local bg fg
	bg="$(theme_hex_to_rgb "${THX[bg]:-#1a1b26}")"
	fg="$(theme_hex_to_rgb "${THX[fg]:-#c0caf5}")"

	local -a order=(black red green yellow blue magenta cyan white)
	local key rgb

	printf '\n  '
	for key in "${order[@]}"; do
		rgb="$(theme_hex_to_rgb "${THX[$key]:-#000000}")"
		printf '\e[48;2;%sm  \e[0m' "$rgb"
	done
	printf '\n  '
	for key in "${order[@]}"; do
		rgb="$(theme_hex_to_rgb "${THX[b$key]:-#555555}")"
		printf '\e[48;2;%sm  \e[0m' "$rgb"
	done
	printf '\n\n'

	local green_rgb blue_rgb red_rgb
	green_rgb="$(theme_hex_to_rgb "${THX[green]:-#00ff00}")"
	blue_rgb="$(theme_hex_to_rgb "${THX[blue]:-#0088ff}")"
	red_rgb="$(theme_hex_to_rgb "${THX[red]:-#ff0000}")"

	printf '  \e[48;2;%sm\e[38;2;%sm%s\e[0m\n' "$bg" "$fg" "  \$ git status                                        "
	printf '  \e[48;2;%sm\e[38;2;%sm%s\e[38;2;%sm%s\e[0m\n' "$bg" "$green_rgb" "  + added_feature.c" "$red_rgb" "   - old_bug.c "
	printf '  \e[48;2;%sm\e[38;2;%sm%s\e[0m\n' "$bg" "$blue_rgb" "  branch: main                                       "
	printf '  \e[48;2;%sm\e[38;2;%sm  Normal / \e[1mBold\e[0;48;2;%sm\e[38;2;%sm / \e[3mItalic\e[0;48;2;%sm\e[38;2;%sm text sample              \e[0m\n' \
		"$bg" "$fg" "$bg" "$fg" "$bg" "$fg"
	printf '\n'
}

# theme_preview <name> -- renders the swatch for an embedded theme.
theme_preview() {
	local name="$1"
	theme_load_hex "$name"
	theme_preview_loaded
}

# theme_load_toml <file> -- parses an Alacritty TOML color theme into the
# global THX array. Uses python3 + tomllib (Python >= 3.11) when available;
# otherwise falls back to best-effort regex extraction.
theme_load_toml() {
	local file="$1"
	THX=()

	local out=""
	if command -v python3 >/dev/null 2>&1 && python3 -c "import tomllib" 2>/dev/null; then
		out="$(THEME_FILE="$file" python3 -c '
import os, tomllib
c = tomllib.load(open(os.environ["THEME_FILE"], "rb")).get("colors", {})
p, n, b, r = c.get("primary", {}), c.get("normal", {}), c.get("bright", {}), c.get("cursor", {})
def v(d, k, default="#000000"):
    val = d.get(k, default)
    return val if isinstance(val, str) else default
out = {"bg": v(p, "background", "#1a1b26"), "fg": v(p, "foreground", "#c0caf5"),
       "cursor": v(r, "cursor", "#c0caf5")}
for k in ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]:
    out[k] = v(n, k)
    out["b" + k] = v(b, k)
for k in sorted(out):
    print(k, out[k])
')"
	fi

	while IFS=' ' read -r key val; do
		[[ -n "$key" ]] && THX[$key]="$val"
	done <<<"$out"
}

# theme_preview_file <file> -- renders the swatch for an arbitrary TOML
# theme file.
theme_preview_file() {
	local file="$1"
	theme_load_toml "$file"
	theme_preview_loaded
}

# themes_fetch_upstream -- clones alacritty/alacritty-theme into
# ~/.config/alacritty/themes-upstream. Requires git + network.
themes_fetch_upstream() {
	local dest="$HOME/.config/alacritty/themes-upstream"
	if [[ -d "$dest/.git" ]]; then
		ui_info "Upstream theme collection already present at $dest, pulling latest..."
		git -C "$dest" pull --ff-only --depth 1 2>&1 | sed 's/^/  /'
	else
		ui_info "Cloning github.com/alacritty/alacritty-theme into $dest ..."
		mkdir -p "$(dirname "$dest")"
		git clone --depth 1 https://github.com/alacritty/alacritty-theme "$dest" 2>&1 | sed 's/^/  /'
	fi
	UPSTREAM_THEME_DIR="$dest/themes"
}

# themes_list_upstream -- populates UPSTREAM_THEME_FILES with .toml paths.
themes_list_upstream() {
	UPSTREAM_THEME_FILES=()
	[[ -d "$UPSTREAM_THEME_DIR" ]] || return 1
	while IFS= read -r f; do
		UPSTREAM_THEME_FILES+=("$f")
	done < <(find "$UPSTREAM_THEME_DIR" -maxdepth 1 -name '*.toml' | sort)
}

# theme_browse_upstream <result_var> -- paged browser for the upstream theme
# collection. Shows 5 themes per page, live-previewing the theme under the
# cursor. Returns the selected file path via <result_var>.
theme_browse_upstream() {
	local -n _result="$1"
	local total="${#UPSTREAM_THEME_FILES[@]}"
	local per_page=5
	local page=0
	local pos=0
	local key

	_ui_tput sc
	while true; do
		_ui_tput rc
		_ui_tput ed
		ui_header "Step 4/17" "Color theme — upstream collection"

		local start=$((page * per_page))
		local end=$((start + per_page))
		[[ "$end" -gt "$total" ]] && end="$total"
		local on_page=$((end - start))

		local i
		for ((i = 0; i < per_page; i++)); do
			local real=$((start + i))
			if [[ "$real" -lt "$end" ]]; then
				local name
				name="$(basename "${UPSTREAM_THEME_FILES[$real]}" .toml)"
				if [[ "$i" -eq "$pos" ]]; then
					printf '  %s> %3d) %s%s\n' "$(ui_color setaf 6)" "$((real + 1))" "$name" "$(ui_color sgr0)"
				else
					printf '    %3d) %s\n' "$((real + 1))" "$name"
				fi
			fi
		done

		theme_preview_file "${UPSTREAM_THEME_FILES[$((start + pos))]}"

		printf '\n'
		ui_rule
		printf '[j/k or up/down] move   [n/p] next/prev page   [Enter] select   [b] back   [r] restart   [q] quit\n' 

		ui_read_key key
		case "$key" in
		UP | k)
			if [[ "$pos" -gt 0 ]]; then
				pos=$((pos - 1))
			elif [[ "$page" -gt 0 ]]; then
				page=$((page - 1))
				pos=$((per_page - 1))
			fi
			;;
		DOWN | j)
			if [[ "$pos" -lt "$((on_page - 1))" ]]; then
				pos=$((pos + 1))
			elif [[ "$(((page + 1) * per_page))" -lt "$total" ]]; then
				page=$((page + 1))
				pos=0
			fi
			;;
		n)
			if [[ "$(((page + 1) * per_page))" -lt "$total" ]]; then
				page=$((page + 1))
				pos=0
			fi
			;;
		p)
			if [[ "$page" -gt 0 ]]; then
				page=$((page - 1))
				pos=0
			fi
			;;
		ENTER)
			_result="${UPSTREAM_THEME_FILES[$((start + pos))]}"
			return 0
			;;
		b)
			return 2
			;;
		r)
			return 3
			;;
		q)
			return 4
			;;
		esac
	done
}
